# This workflow automates the creation of a weekly pull request that provides an intermediary during a sprint cycle.
#
#
# Each Thursday morning, at 10:00am EST, this job runs, creating a pull request that requests approval for merging
# the latest changes from `develop` to the `SNKRS-release-integration` branch.  Upon approval, said changes from
# the `develop` branch will then be merged to `SNKRS-release-integration`, and upon completion of the sprint
# and release cycle, the changes from `SNKRS-release-integration` will be merged into `SNKRS-production`.

name: SNKRS-Release-Weekly-PR-Automation

# Timing controls for the workflow's actions.
# Runs the automation every Thursday at 10:00am (time zone support is not
# yet available.  The CRON job defaults to UTC, or +5 from EST).
on:
  #schedule:
    #- cron: '*/15 * * * *'
  push:
    - branches:
      - test-automation

  # Allows the automation to be run manually from the Workflows pane.
  workflow_dispatch:
  
# The jobs to be run when the automation is triggered, either by schedule or
# when run manually.
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: read-app-version
      id: readappversion
      run: echo "::set-output name=version::$(cat snkrs/SNKRS.xcconfig | grep -m1 'APPLICATION_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' ')"
    - name: get-current-date
      id: getcurrentdate
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: create-weekly-branch
      run: git checkout -b SNKRS-${{ steps.readappversion.outputs.version }}-Weekly-${{ steps.getcurrentdate.outputs.date }}
    - name: Push new branch
      run: git push SNKRS-${{ steps.readappversion.outputs.version }}-Weekly-${{ steps.getcurrentdate.outputs.date }}
    - name: generate-pr-title
      id: generateprtitle
      run: echo "::set-output name=prtitle::[${{ steps.readappversion.outputs.version }}] [Release Integration] Weekly RC Merge to SNKRS-release-integration"
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "SNKRS-${{ steps.readappversion.outputs.version }}-Weekly-${{ steps.getcurrentdate.outputs.date }}"
        destination_branch: "SNKRS-release-integration"
        pr_title: ${{ steps.generateprtitle.outputs.prtitle }}
        pr_body: "This is an automated pull request to merge the latest changes from develop into SNKRS-release-integration."
        pr_draft: false
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
